site_name: Spilo PostgreSQL appliance
repo_url: https://github.com/zalando/spilo/

pages:
- Introduction:
  - 'Overview': 'README.md'
  - 'Design': 'DESIGN.md'
- User guide:
  - 'Prerequisites for deployment': 'user-guide/prerequisites.md'
  - 'Deploying etcd': 'docs/user-guide/deploy_etcd.md'
  - 'Deploying spilo': 'docs/user-guide/deploy_spilo.md'
- Components:
  - 'Governor': 'docs/components/governor.md'
  - 'Etcd proxy': 'docs/components/etcd-proxy.md'
