pages:
- ['docs/README.md', 'Introduction']
- ['docs/DESIGN.md', 'Design']
- ['docs/user-guide/prerequisites.md', 'User Guide', 'Prerequisites for deployment']
- ['docs/user-guide/deploy_etcd.md', 'User Guide', 'Deploying etcd']
- ['docs/user-guide/deploy_spilo.md', 'User Guide', 'Deploying spilo']
- ['docs/components/governor.md', 'Components', 'Governor']
- ['docs/components/etcd-proxy.md', 'Components', 'Etcd proxy']
