site_name: Spilo PostgreSQL appliance
repo_url: https://github.com/zalando/spilo/
theme: readthedocs

pages:
  - Introduction: index.md
  - Design: DESIGN.md
  - User Guide:
    - Connect to spilo: user-guide/connect_spilo.md
  - Tutorial:
    - Prerequisites: tutorial/prerequisites.md
    - Deploy spilo: tutorial/deploy_spilo.md
  - Administrator Guide:
    - Sizing spilo: admin-guide/sizing.md
    - Scaling up or down: admin-guide/scaling.md
